### ISSUE TITLE
Add ORM

### ISSUE THREAD

**Issue by rokumura7** [rokumura7/penguinhouse_api#7]
Before adding an ORM library on the app, I would like to know what kinds of ORMs are available for playframework.

**Comment by lilycoco** [comment]
https://www.playframework.com/documentation/2.8.x/Introduction#What-is-Play?

> Play is non-opinionated about database access, and integrates with many object relational mapping (ORM) layers. It supports Anorm, Slick, and JPA out of the box, but many customers use NoSQL or other ORMs.

It says "Play is non-opinionated about database access"😇
My company uses [Skinny-ORM](http://skinny-framework.org/documentation/orm.html) but the document is kind of hard to read..

**Comment by rokumura7** [comment]
- [ScalikeJDBC](http://scalikejdbc.org/)
- [Slick](https://scala-slick.org/)
- [jOOQ](https://www.jooq.org/)
- [EbeanORM](https://ebean.io/)

ちょっと日本語で書くけど、
ScalaはJava資源を使えるからJava製のものも選択肢に入りうるとは思う。
例えばjOOQやEbeanも確か元々Javaのものだったはず。
あとJavaで有名なのだとMyBatisとかDOMAとか。あ、てか、JPAもJavaか。
まあ色々あります:+1:

ただ、口頭でも話したけど一旦Raw SQLを書く方向も良いなと思いました。
DBやSQLの勉強にもなるし:pig:
まあORM使うとしても基本CRUDのSQLは読み書きできるようになりたいね！

あと、たぶん「Scala ORM」とかって調べてると、ORMなんていらないだろう、みたいな記事も結構出てきたんじゃないかな？あれ、なんでなんでしょうね？:innocent:

とりあえず、技術選定をしていただきたく！
技術選定に関しては[この記事](https://note.com/timakin/n/n2d9eaa02e633)が結構いいなーと思ってます！
今回は要件とかよく分からんし「モチベーション」と「信頼性（情報量って考えてもいいです）」の2軸とかでもいいですね。

**Comment by lilycoco** [comment]
Use raw SQL for now!
